package com.tcgsupport.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * 試合テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="GAME_TBL")
public class GameTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** game_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer gameId;

	/** 大会テーブル. */
	private TornTblEntity tornTbl;

	/** 新規テーブル. */
	private Integer userId1;
	@OneToOne
    @JoinColumn(name="userId",insertable=false ,updatable=false)
	private UserTblEntity user1Tbl;

	/** 新規テーブル. */
	private Integer userId2;
	@OneToOne
    @JoinColumn(name="userId",insertable=false ,updatable=false)
	private UserTblEntity user2Tbl;

	/** table_no. */
	private Integer tableNo;

	/** state. */
	private Integer state;

	/** round. */
	private Integer round;

	/** type. */
	private Integer type;

	/** result. */
	private Integer result;

	/**
	 * コンストラクタ.
	 */
	public GameTblEntity() {
	}
}
