package com.tcgsupport.entity;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * オーガナイザー モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
 @Entity 
 @Table(name="ORGANIZER_TBL")
public class OrganizerTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	/** 大会テーブル. */
	private Integer tornId;
	@OneToOne
    @JoinColumn(name="tornId",insertable=false ,updatable=false)
	private TornTblEntity tornTbl;

	/** 新規テーブル. */
	private Integer organizerUserId;
	@OneToOne
    @JoinColumn(name="userId",insertable=false ,updatable=false)
	private UserTblEntity organizerUserTbl;

	/** main_flg. */
	private Integer mainFlg;

	/**
	 * コンストラクタ.
	 */
	public OrganizerTblEntity() {
	}


}
