package com.tcgsupport.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * 仮ユーザーテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="PROV_USER_TBL")
public class ProvUserEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	/** mail. */
	private String mail;

	/** token. */
	private String token;

	/** limit. */
	private Date expirationDate;


	private Integer userId;
	/**
	 * コンストラクタ.
	 */
	public ProvUserEntity() {
	}
}
