package com.tcgsupport.entity;

import java.io.Serializable;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * ルールテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="RULE_TBL")
public class RuleTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** rule_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer ruleId;

	/** 大会テーブル. */
	private Integer tornId;
	@OneToOne
    @JoinColumn(name="tornId",insertable=false ,updatable=false)
	private TornTblEntity tornTbl;

	/** timeout. */
	private Integer timeout;

	/** win_point. */
	private Integer winPoint;

	/** draw_point. */
	private Integer drawPoint;

	/** lower_win_rate. */
	private Integer lowerWinRate;


	/**
	 * コンストラクタ.
	 */
	public RuleTblEntity() {
	}
}
