package com.tcgsupport.entity;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * シリーズポイント モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="SERIES_POINT_TBL")
public class SeriesePointEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	
	/** 新規テーブル. */
	private SeriesTblEntity seriesTbl;

	/** 新規テーブル. */
	private UserTblEntity userTbl;

	/** point. */
	private Integer point;

	/**
	 * コンストラクタ.
	 */
	public SeriesePointEntity() {
	}


}
