package com.tcgsupport.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.Data;

/**
 * 新規テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="SERIES_TBL")
public class SeriesTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** series_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer seriesId;

	/** name. */
	private String name;

	/** discription. */
	private String discription;

	/** icon. */
	private String icon;

	/** シリーズポイント 一覧. */
	@OneToMany(cascade = CascadeType.ALL)
	@JoinColumn(name="seriesId",insertable=true ,updatable=true)
	private Set<SeriesePointEntity> seriesePointSet;

	/** 大会テーブル 一覧. */
	@OneToMany(cascade = CascadeType.ALL)
	@JoinColumn(name="seriesId",insertable=true ,updatable=true)
	private Set<TornTblEntity> tornTblSet;

	/**
	 * コンストラクタ.
	 */
	public SeriesTblEntity() {
		this.seriesePointSet = new HashSet<SeriesePointEntity>();
		this.tornTblSet = new HashSet<TornTblEntity>();
	}

}
